### ISSUE TITLE
Files in groupfolders are never shown as recommended

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/recommendations#341]
Having groupfolders installed, files which are inside groupfolders are never shown in the recommendations list. I would expect this app to include files within groupfolders.

Is this behavior as intended or is this rather a bug (I can give more details in this case)?
If this is intended, can you think about to change it? :)

**Comment by ChristophWurst** [comment]
We use the files app's *recent files* API for this. So also that tab in the Files app won't give you those files.

This has to be fixed in the server code or groupfolder. I'm not sure what code is responsible for this.

In any case it's low priority for us to change this. If you are a customer please send us an email to the support system and we can prioritize this higher. If you're a developer, you're very welcome to dig into the code, find the relevant sections and try your luck improving the logic :v:
